export const slides = [
  {
    heading: 'Come experience the magic',
    desc: 'Afrifoods gives you the best traditional and exotic dishes in Nigeria. Rich in flavour, healthy and very satisfying',
    image: require('./images/home-1.jpg')
  },
  {
    heading: 'Feel the taste!',
    desc: 'Afrifoods gives you the best traditional and exotic dishes in Nigeria. Rich in flavour, healthy and very satisfying',
    image: require('./images/home-2.jpg')
  },
  {
    heading: 'Crunchy and yummy!',
    desc: 'Afrifoods gives you the best traditional and exotic dishes in Nigeria. Rich in flavour, healthy and very satisfying',
    image: require('./images/home-3.jpg')
  },
]

export const categories = [
  {
    id: "price_1M5uLBL6uK8D8AK8QgncrGoO",
    category: "Rice",
    image: require("./images/rice-1.png"),
    desc: "Jollof Rice",
    price: "1500",
    button: "Add to cart",
  },
  {
    id: "price_1M5uNQL6uK8D8AK8xKoN0XSh",
    category: "Soup",
    image: require("./images/soup-1.png"),
    desc: "Banga Soup",
    price: "1800",
    button: "Add to cart",
  },
  {
    id: "price_1M5uP9L6uK8D8AK8Z2r30RXW",
    category: "Sauce",
    image: require("./images/stew-1.png"),
    desc: "Garden Egg Sauce",
    price: "2000",
    button: "Add to cart",
  },
  {
    id: "price_1M5uT3L6uK8D8AK8d6so8vmd",
    category: "Fries",
    image: require("./images/fries-1.png"),
    desc: "Potatoe Fries",
    price: "500",
    button: "Add to cart",
  },
  {
    id: "price_1M5uTyL6uK8D8AK81j5yApYK",
    category: "Soup",
    image: require("./images/soup-2.png"),
    desc: "Bitter Leaf Soup",
    price: "1400",
    button: "Add to cart",
  },
  {
    id: "price_1M5uUzL6uK8D8AK8F0JZNK00",
    category: "Rice",
    image: require("./images/rice-2.png"),
    desc: "Coconut Rice",
    price: "1500",
    button: "Add to cart",
  },
  {
    id: "price_1M5uVpL6uK8D8AK8lr5VDeiO",
    category: "Sauce",
    image: require("./images/stew-2.png"),
    desc: "Native Sauce",
    price: "1000",
    button: "Add to cart",
  },
  {
    id: "price_1M5uWfL6uK8D8AK8lxIEY2aD",
    category: "Fries",
    image: require("./images/fries-2.png"),
    desc: "Akara Fries",
    price: "500",
    button: "Add to cart",
  },
  {
    id: "price_1M5uYBL6uK8D8AK832evBn1w",
    category: "Rice",
    image: require("./images/rice-3.png"),
    desc: "White Rice & Stew",
    price: "1000",
    button: "Add to cart",
  },
  {
    id: "price_1M5uYyL6uK8D8AK8I5YjnM3q",
    category: "Soup",
    image: require("./images/soup-3.png"),
    desc: "Afang Soup",
    price: "1400",
    button: "Add to cart",
  },
  {
    id: "price_1M5uZfL6uK8D8AK85ZmjKPiT",
    category: "Fries",
    image: require("./images/fries-3.png"),
    desc: "Yam Fries",
    price: "600",
    button: "Add to cart",
  },
  {
    id: "price_1M5uafL6uK8D8AK8tWYQXj7a",
    category: "Sauce",
    image: require("./images/stew-3.png"),
    desc: "Ofada Sauce",
    price: "1100",
    button: "Add to cart",
  },
  {
    id: "price_1M5ubeL6uK8D8AK8dhdTH2Nk",
    category: "Soup",
    image: require("./images/soup-4.png"),
    desc: "Efo Soup",
    price: "1300",
    button: "Add to cart",
  },
  {
    id: "price_1M5ucVL6uK8D8AK83RT3OR6X",
    category: "Soup",
    image: require("./images/soup-5.png"),
    desc: "Egusi Soup",
    price: "1300",
    button: "Add to cart",
  },
  {
    id: "price_1M5udCL6uK8D8AK8N9jkLhs4",
    category: "Fries",
    image: require("./images/fries-4.png"),
    desc: "Plantain Fries",
    price: "600",
    button: "Add to cart",
  },
  {
    id: "price_1M5udsL6uK8D8AK8PsGMXHTU",
    category: "Rice",
    image: require("./images/rice-4.png"),
    desc: "Fried Rice",
    price: "1300",
    button: "Add to cart",
  },
  {
    id: "price_1M5ueXL6uK8D8AK8bKlKZKov",
    category: "Sauce",
    image: require("./images/stew-4.png"),
    desc: "Redoil Sauce",
    price: "1000",
    button: "Add to cart",
  },
  {
    id: "price_1M5ufLL6uK8D8AK8HEgvHsBD",
    category: "Soup",
    image: require("./images/soup-6.png"),
    desc: "Ogbono Soup",
    price: "1300",
    button: "Add to cart",
  },
];